server:
  port: 9100

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.99.240.244:3306/test?useSSL=false
#    username: root
#    password: dw@lrrAnd1314
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/wei_chat?useSSL=false
    username: root
    password: root
  rabbitmq:
    host: 47.99.240.244
    port: 5672
    username: root
    password: root
  redis:
    host: 47.99.240.244
    port: 6379
    database: 1
    password: 123456
    pool:
      max-active: 8           #连接池最大连接数
      max-wait: 1             #连接池最大阻塞等待时间
      max-idle: 8             #连接池最大空闲链接
      min-idle: 0             #连接池最小空闲链接
    timeout: 20000            #连接超时时间

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

fdfs:
  connect-timeout: 600
  so-timeout: 1500
  tracker-list: 192.168.1.105:22122
  thumb-image:
    height: 150
    width: 150
  resHost: 192.168.1.105
  pool:
    jmx-enabled: false
