server:
  port: 9100

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.240.244:3306/test?useSSL=false
    username: root
    password: dw@lrrAnd1314
  rabbitmq:
    host: 47.99.240.244
    port: 5672
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

# 测试git提交